- name: Setup environment for deployment
  hosts: localhost
  become: true
  tasks:
    - name: Update apt sources
      copy:
        dest: /etc/apt/sources.list.d/ubuntu.list
        content: |
          deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ jammy main restricted
          deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ jammy-updates main restricted
          deb http://security.ubuntu.com/ubuntu jammy-security main restricted

    - name: Update apt packages
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600  # Only update if cache is older than 1 hour

    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: no  # Already updated above
      loop:
        - docker.io
        - docker-compose
        - python3-pip  # Often needed for Docker SDK

    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes
