- name: Setup environment for deployment
  hosts: localhost
  become: true
  tasks:
    - name: Update apt packages
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
