name: CI/CD Pipeline for Static Website

on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    
    steps:
      # Add Docker permissions step
      - name: Setup Docker permissions
        run: |
          sudo chmod 666 /var/run/docker.sock
          sudo usermod -aG docker $USER
          
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for advanced Docker features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
          
      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: List files in the directory
        run: ls -al
        
      # Build and push Docker image using Buildx
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-static-website:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-static-website:latest
          cache-to: type=inline
          
      # Set up SSH for Ansible deployment
      - name: Set up SSH for Ansible
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      # Run Ansible Playbook
      - name: Run Ansible Playbook for Deployment
        uses: dawidd6/action-ansible-playbook@v2
        with:
          inventory: ansible/inventory
          playbook: ansible/playbook.yml
          options: |
            --become
            --become-method=sudo
          sudo: true

      - name: Notify on failure
        if: failure()
        run: |
          echo "Workflow failed! Check the logs for more details."
