name: CI/CD Pipeline for Static Website

# Trigger the workflow only when changes are pushed to the 'src' folder
on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3
        
      # Set up Docker Buildx for advanced Docker features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      # Log in to Docker Hub (or any registry you are using)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      # List files in the directory to confirm correct path
      - name: List files in the directory
        run: ls -al
        
      # Build and push Docker image using Buildx
      - name: Build and push Docker image
        uses: docker/build-push-action@v4  # Using the official Docker build-push action
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/my-static-website:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/my-static-website:latest
          cache-to: type=inline
          
      # Set up SSH for Ansible deployment
      - name: Set up SSH for Ansible
        uses: webfactory/ssh-agent@v0.8.0  # Updated to latest version
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      # Run the Ansible Playbook to deploy the static website
      - name: Run Ansible Playbook for Deployment
        uses: dawidd6/action-ansible-playbook@v2
        with:
          inventory: ansible/inventory
          playbook: ansible/playbook.yml
          options: |
            --become
            --become-method=sudo
          sudo: true  # Added sudo permission

      # Add error notification (optional but recommended)
      - name: Notify on failure
        if: failure()
        run: |
          echo "Workflow failed! Check the logs for more details."
          # You can add more notification methods here (e.g., email, Slack)
